version: "3.7"
services:
 app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: notebooktest
    container_name: notebooktest-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - notebooktest

 db:
    image: mysql:5.7
    container_name: notebooktest-db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel_notebooktest
      #MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      #MYSQL_PASSWORD: ${DB_PASSWORD}
      #MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - notebooktest

 nginx:
    image: nginx:1.17-alpine
    container_name: notebooktest-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - notebooktest

networks:
  notebooktest:
    driver: bridge
